"""Repository contracts.

Storage backends implement these Protocols. The rest of the app depends only
on the contracts, so the SQLite implementation can be swapped (or faked in
tests) without touching business logic.
"""
from __future__ import annotations

from typing import Protocol, Sequence, Optional, runtime_checkable

from .models import (
    Achievement,
    AttemptResult,
    LessonProgress,
    Profile,
    UnlockedAchievement,
)


@runtime_checkable
class ProfileRepository(Protocol):
    def create(self, name: str, avatar: str = "default") -> Profile: ...
    def get(self, profile_id: str) -> Optional[Profile]: ...
    def list_all(self) -> Sequence[Profile]: ...
    def update(self, profile: Profile) -> Profile: ...
    def delete(self, profile_id: str) -> bool: ...


@runtime_checkable
class AttemptRepository(Protocol):
    def add(self, result: AttemptResult) -> AttemptResult: ...
    def list_by_profile(self, profile_id: str, limit: int = 50) -> Sequence[AttemptResult]: ...
    def best_for_lesson(self, profile_id: str, lesson_id: str) -> Optional[AttemptResult]: ...
    def count_for_lesson(self, profile_id: str, lesson_id: str) -> int: ...


@runtime_checkable
class ProgressRepository(Protocol):
    def get(self, profile_id: str, lesson_id: str) -> Optional[LessonProgress]: ...
    def upsert(self, progress: LessonProgress) -> LessonProgress: ...
    def list_for_profile(self, profile_id: str) -> Sequence[LessonProgress]: ...
    def list_unlocked_lessons(self, profile_id: str) -> Sequence[str]: ...


@runtime_checkable
class AchievementRepository(Protocol):
    def list_definitions(self) -> Sequence[Achievement]: ...
    def register_definition(self, achievement: Achievement) -> None: ...
    def unlock(self, profile_id: str, achievement_id: str) -> Optional[UnlockedAchievement]: ...
    def list_unlocked(self, profile_id: str) -> Sequence[UnlockedAchievement]: ...
    def is_unlocked(self, profile_id: str, achievement_id: str) -> bool: ...
